
name: Build
run-name: Build ${{ github.sha }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cmake -S . -B cmake-build-debug
      - run: cmake --build cmake-build-debug
