
name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cmake -S . -B cmake-build-debug
      - run: cmake --build cmake-build-debug --target stagt
      - uses: actions/upload-artifact@master
        with:
          name: test-binary
          path: cmake-build-debug/stagt
      - uses: actions/upload-artifact@master
        with:
          name: shared-library
          path: cmake-build-debug/stag_lib/stag.so

  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      - name: Install Sphinx
        run: sudo apt-get install -y python3-sphinx
      - name: Install Breathe
        run: sudo python3 -m pip install breathe
      - name: Install RTD Theme
        run: sudo python3 -m pip install furo
      - name: Build Docs
        run: |
          cmake -S . -B cmake-build-debug
          cmake --build cmake-build-debug --target Documentation

  Test:
    runs-on: ubuntu-latest
    needs: Build
    env:
      LD_LIBRARY_PATH: ${{ github.workspace }}/stag_lib
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: test-binary
          path: .
      - uses: actions/download-artifact@master
        with:
          name: shared-library
          path: stag_lib/
      - run: chmod +x stagt
      - name: Run Tests
        run: ./stagt
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            test-binary
            shared-library
