
name: Build
run-name: Build ${{ github.sha }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cmake -S . -B cmake-build-debug
      - run: cmake --build cmake-build-debug
      - uses: actions/upload-artifact@master
        with:
          name: test-binary
          path: cmake-build-debug/stagt
      - uses: actions/upload-artifact@master
        with:
          name: shared-library
          path: cmake-build-debug/stag_lib/stag.so

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: test-binary
          path: .
      - uses: actions/download-artifact@master
        with:
          name: shared-library
          path: stag_lib/
      - run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/stag_lib/
      - run: export LD_LIBRARY_PATH
      - run: echo $LD_LIBRARY_PATH
      - run: ls -ltrh ./stag_lib/
      - run: chmod +x stagt
      - name: Run Tests
        run: ./stagt
