
name: Test
on: [push]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Eigen
        run: sudo apt-get install -y libeigen3-dev
      - name: Install Spectra
        run: |
          wget https://github.com/yixuan/spectra/archive/v1.0.1.tar.gz
          tar xzvf v1.0.1.tar.gz
          cd spectra-1.0.1/
          mkdir build && cd build
          cmake ..
          sudo make all && sudo make install
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cmake -S . -B cmake-build-release -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build cmake-build-release --target stagt
      - uses: actions/upload-artifact@master
        with:
          name: test-binary-linux
          path: cmake-build-release/stagt
      - uses: actions/upload-artifact@master
        with:
          name: shared-library-linux
          path: cmake-build-release/stag_lib/stag.so

  Test-Linux:
    runs-on: ubuntu-latest
    needs: Build-Linux
    env:
      LD_LIBRARY_PATH: ${{ github.workspace }}/stag_lib
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: test-binary-linux
          path: .
      - uses: actions/download-artifact@master
        with:
          name: shared-library-linux
          path: stag_lib/
      - run: chmod +x stagt
      - name: Run Tests
        run: ./stagt
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            test-binary-linux
            shared-library-linux

  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Install Eigen
        run: |
          curl --output eigen-3.4.0.zip https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
          unzip eigen-3.4.0.zip
          cd eigen-3.4.0
          mkdir build
          cd build
          cmake ..
          cmake --build . --target install
          cd ..\..
      - name: Install Spectra
        run: |
          curl --output v1.0.1.zip -L0 https://github.com/yixuan/spectra/archive/v1.0.1.zip
          unzip v1.0.1.zip
          cd spectra-1.0.1
          mkdir build
          cd build
          cmake ..
          cmake --build . --target install
          cd ..\..
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cmake -S . -B cmake-build-release -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build cmake-build-release --target stagt
      - uses: actions/upload-artifact@master
        with:
          name: test-binary-windows
          path: cmake-build-release/stagt
      - uses: actions/upload-artifact@master
        with:
          name: shared-library-windows
          path: cmake-build-release/stag_lib/stag.so

  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Eigen
        run: sudo apt-get install -y libeigen3-dev
      - name: Install Spectra
        run: |
          wget https://github.com/yixuan/spectra/archive/v1.0.1.tar.gz
          tar xzvf v1.0.1.tar.gz
          cd spectra-1.0.1/
          mkdir build && cd build
          cmake ..
          sudo make all && sudo make install
      - name: Install Doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz
          tar xzvf doxygen-1.9.6.linux.bin.tar.gz
          sudo cp doxygen-1.9.6/bin/doxygen /usr/bin/doxygen
          sudo chmod +x /usr/bin/doxygen
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Docs
        run: |
          cmake -S . -B cmake-build-release -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build-release --target Documentation
